---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tesla-public-key
data:
  # Non-secret EC P-256 public key. Must match the private key at
  # HA's config/tesla_fleet.key (generated together via openssl).
  com.tesla.3p.public-key.pem: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEh5ur3PRFsJ16HmHd8IWU92GbyUbZ
    QrQu2OShB+CkScC7cH+12mL9YHVP9PR3IeyMW1RJJufigVgL33bzMpvwqQ==
    -----END PUBLIC KEY-----
