FROM docker.io/library/ubuntu:25.10

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY pms-backup.sh .
RUN chmod +x pms-backup.sh

ENTRYPOINT ["/app/pms-backup.sh"]
