apiVersion: v1
data:
  values.yaml: YWRkaXRpb25hbFZvbHVtZU1vdW50czoKLSBuYW1lOiB1c2ItemJ0MgogIG1vdW50UGF0aDogL2Rldi90dHlBQ00wCi0gbmFtZTogZGJ1cwogIG1vdW50UGF0aDogL3J1bi9kYnVzCiAgcmVhZE9ubHk6IHRydWUKYWRkaXRpb25hbFZvbHVtZXM6Ci0gbmFtZTogdXNiLXpidDIKICBob3N0UGF0aDoKICAgIHBhdGg6IC9kZXYvc2VyaWFsL2J5LWlkL3VzYi1OYWJ1X0Nhc2FfWkJULTJfRENCNEQ5MEMxNDZDLWlmMDAKICAgIHR5cGU6IENoYXJEZXZpY2UKLSBuYW1lOiBkYnVzCiAgaG9zdFBhdGg6CiAgICBwYXRoOiAvcnVuL2RidXMKICAgIHR5cGU6IERpcmVjdG9yeQo=
kind: Secret
metadata:
  name: home-assistant-values
  namespace: default
