apiVersion: v1
data:
  values.yaml: cGVyc2lzdGVuY2U6CiAgdXNiLXpidDI6CiAgICBlbmFibGVkOiB0cnVlCiAgICB0eXBlOiBob3N0UGF0aAogICAgaG9zdFBhdGg6IC9kZXYvc2VyaWFsL2J5LWlkL3VzYi1OYWJ1X0Nhc2FfWkJULTJfRENCNEQ5MEMxNDZDLWlmMDAKICAgIGhvc3RQYXRoVHlwZTogQ2hhckRldmljZQogICAgbW91bnRQYXRoOiAvZGV2L3R0eUFDTTAKICBkYnVzOgogICAgZW5hYmxlZDogdHJ1ZQogICAgdHlwZTogaG9zdFBhdGgKICAgIGhvc3RQYXRoOiAvcnVuL2RidXMKICAgIGhvc3RQYXRoVHlwZTogRGlyZWN0b3J5CiAgICBtb3VudFBhdGg6IC9ydW4vZGJ1cwogICAgcmVhZE9ubHk6IHRydWUK
kind: Secret
metadata:
  name: home-assistant-values
  namespace: default
