---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex-backup
  namespace: kube-system
spec:
  interval: 1h0m0s
  path: ./infrastructure/cronjob/
  sourceRef:
    kind: GitRepository
    name: k8s-infrastructure
    namespace: kube-system
  prune: true
  targetNamespace: default
  postBuild:
    substitute:
      CRONJOB_NAME: plex-backup
      NAMESPACE: default
      SCHEDULE: "0 3 * * *"
      IMAGE: docker.io/gandazgul/plex-backup:latest
  patches:
    - patch: |
        - op: add
          path: /spec/jobTemplate/spec/template/spec/volumes/-
          value:
            name: backup-volume
            persistentVolumeClaim:
              claimName: backup-volume
        - op: add
          path: /spec/jobTemplate/spec/template/spec/volumes/-
          value:
            name: yasr-volume
            persistentVolumeClaim:
              claimName: yasr-volume
      target:
        kind: CronJob
    - patch: |
        - op: add
          path: /spec/jobTemplate/spec/template/spec/containers/0/volumeMounts/-
          value:
            name: yasr-volume
            mountPath: /media/plexmediaserver
            subPath: configs/plex/Library/Application\ Support/Plex\ Media\ Server/
        - op: add
          path: /spec/jobTemplate/spec/template/spec/containers/0/volumeMounts/-
          value:
            name: backup-volume
            mountPath: /media/backup
            subPath: plex-backup
      target:
        kind: CronJob
    - patch: |
        - op: add
          path: /spec/jobTemplate/spec/template/spec/containers/0/env
          value:
            - name: PLEX_IP
              value: "${CONTROL_PLANE_IP}"
            - name: BACKUP_LOC
              value: "/media/backup"
            - name: PMS_DIR
              value: "/media/plexmediaserver"
            - name: LOGFILE
              value: "/media/plexmediaserver/pms-backup.log"
      target:
        kind: CronJob
