---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: default
spec:
  chart:
    spec:
      chart: mosquitto
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  dependsOn:
    - name: yasr-volume
  interval: 1h0m0s
  values:
    # TODO: why does it have to be NodePort?
    service:
      main:
        type: NodePort
        ports:
          mqtt:
            enabled: true
            port: 1883
            nodePort: 1883
    persistence:
#      yasr:
#        enabled: true
#        existingClaim: yasr-volume
#        subPath:
#          - path: configs/mosquitto/data
#            mountPath: /mosquitto/data
#          - path: configs/mosquitto
#            mountPath: /mosquitto/configinc
#      configinc:
#        enabled: true
      data:
        enabled: true
        existingClaim: yasr-volume
        mountPath: /mosquitto
        subPath: configs/mosquitto/

