---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate
  namespace: default
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: teslamate
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: yasr-volume
  values:
    image:
      repository: teslamate/teslamate
      pullPolicy: Always
      tag: 1.27.2
    env:
      TZ: "America/New_York"
      DATABASE_USER: "teslamate"
      DATABASE_NAME: "teslamate"
      DATABASE_HOST: teslamate-postgresql
      DISABLE_MQTT: "false"
      MQTT_HOST: "emqx"
      MQTT_USERNAME: "mqtt"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: teslamate.${INGRESS_INTERNAL_NAME}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - teslamate.${INGRESS_INTERNAL_NAME}
    postgresql:
      enabled: true
      securityContext:
        enabled: true
        fsGroup: 1000
      containerSecurityContext:
        enabled: true
        runAsUser: 1000
      postgresqlUsername: teslamate
      postgresqlPassword: teslamate
      postgresqlDatabase: teslamate
      persistence:
        enabled: true
        existingClaim: yasr-volume
        mountPath: /bitnami/postgresql
        subPath: configs/teslamate/database
  valuesFrom:
  - kind: Secret
    name: "teslamate-values"
    optional: false