---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: zigbee2mqtt
      version: '1.37.1'
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: kube-system
      interval: 5m
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.35.3
    config:
      homeassistant: true
      mqtt:
        server: "mqtt://10.1.1.2"
      serial:
        port: /dev/ttyUSB0
      frontend:
        port: 8080
    env:
      TZ: "${CLUSTER_TIME_ZONE}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: zigbee.${CLUSTER_DOMAIN_NAME}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - zigbee.${CLUSTER_DOMAIN_NAME}
            secretName: internal-ingress-cert
        annotations:
          kubernetes.io/ingress.class: "nginx"
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: ""
    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB0
      data:
        enabled: true
        mountPath: /data
        existingClaim: yasr-volume
        subPath: configs/zigbee2mqtt
    securityContext:
      privileged: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
