---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
imagePullSecrets:
  - name: dockerhub-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: kube-system
imagePullSecrets:
  - name: dockerhub-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: monitoring
imagePullSecrets:
  - name: dockerhub-creds
