---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAiBQCWE2q2bgNh2s5xHufusYMZQc6hOBT4JqrXc2d/QCfbimeh7VvFGk8s3kt4+fslPpiN0cWtnRyW5x1f7TQJ/UX7ZUil1wfO4mE2uksBqpzySlQEhRNZkWzEclL5PfDFqdkXRxj5Dovfi217bNLGrGh/NBBzMThMyqFW2Ev6eRLQofDVNZrAZ1UvurdV4cQIR1UzfLZD1tKSpTo2e8wnr5dBQgxFeM1JX+xLHgCZBZtE8iLxtCFU34sUV2NRuqnhe5M8KN7+cNZlrP2Q3FFo2HuKAIPu/CZbSOJLhxFdG4US1BA/H5Xbxxz7NnDSZp2thi8gK8KFHw63RHIITzadBK5btNE/s0NaIQkOzbctaN+79gPbpM/mPFM9Q8+dLz+ejuFKlWqCCH39WjxFaDKASEi+jfzKtiMP/rRhHww7C3DsAD9XXOwhniKSDSZR9eNQLUSNEYoh/8jTc+wFH1bMYAkOYHLIHd8PTXHP4GPH4sN46txe9A9mM46Y5LcKUZRxs/ZkwNSvkjvbfFY+mUjD+Ba3HJ4/71zlTUaFqQRp1kVOlc8z7/JkSoqOzP+aQ+0CJjSOtt9cuhTNCfTOo3Y/1G5LM4DD4crtcjL/YfF7y+abp8sm6EPpu62lHWHo74fCmEkveOhhKKlH7o51b/Gg+/6pze+hkxenBn2adWzwwAd71bmXPijTQBKj6aIgnpo0Dy1t6/WbYLrQ1ncVFm6wdTUGe6W2lq4aFxvcXLSU+hvGOf+JXk+3K7M8rLloXzdsgjdi7svvlDVhYE6Tyd3hIwTEqHVLsQ1A7P+HG3YnVu+0qW1HgkNPbrOovY6AlaxrFCFTSJRQfG8k4yIyNdicwRA7kgo0SjetgO7x3ibc7vgsNv+NybEbeC+xPa7P/u6QredKr4beDgxwsusW1HIyTHKaiArUFGdtNlqTXWQD45hoOaRkA/PJX9kzTDIbNLhQuTdNQ9llLgVWsboMpDL63JVexg==
  template:
    metadata:
      name: ghcr-creds
      namespace: default
    type: kubernetes.io/dockerconfigjson
