---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCwMV/mmftIpuFWI3X98dYpims+w8ilribbj2w1s6uxcLmqYpDdq1qMYZ87UGqRxROel+PmkngJUpCbYrl5yPBxPCxvwpO+G5kg862BEa2/ORzY4DQUMbp+cQV539oXsQJjc7FPxesKsBrQoIn7h4pMuYeAlfXbPQt+TlUORLpcJh3kNB5Kc6oMWH48WrW1THe3D9JPsCgoeniWiAkooy+vidnaMcSlgn/hYWdU/IiOEHj1ApioUdl4dawUT7ulVxjk5k4CmUF5lMvz5htSALK05O0WZKgiOgvHlAfErqPJlWqkI4OF/a2PPCpJru4pOAXO2exZ1yk6D1nUKNIKeb6MBrgHJ4JjLN8oxMfurlhpWEVg0ASJsl0EeZcK/qFRdmLsjFkPQZ8SyUZ7AgjDUBGRgFPLMFWWDX+aZSJKCLw7QuMcYLyDb5EtXonegXLf65d8OgFHbHX8vG61xjn5NHUzQv87X8CqfRzwBUTBhne56E1Qu7npWwneaT+tqBeJZV+OBWcSX9j49j4AFN+8tUd8EZMizd+ZN+0jWNmYhZg6kYINiHczBiKesOFh8tiSgiEWfJ9GgnsyN/eXMwbMZY9HDFf9EWw+zZBXEUDtHNLJoCpU2MkUluc++U7YvE//GJPsStyfR2/k8oJFuM7PFLaFkYekXr0bEtyw/ZK2io0Nemswnm4KdZRlaeMXjZys2+ZlhK4wHkbAr72Eu1DlNmbBy+FH/iQISkEygjMxSbK/3T+ITDsYM6eTT4c6p44l4Yu6ZM0Lsxmh1P+WtHsZYa3ScCklJKQO/RN5btpqrdlXKjJKninkO3cha0pAZfL9Qac3h+N5FAguR40TkLhd86Gs7OL+vnVpqey14aLUPfkqkU+Jp72raVvlRDUgrEZYp+cINnIelnxA8tv44y/tWbw/p2L5yN9l0vdRhlAENL/sxcdl/W/4plIc2Fjt1MNMGae5WVhVqpwMa/7rnl9xUorIc2sLrA==
  template:
    metadata:
      name: ghcr-creds
      namespace: default
    type: kubernetes.io/dockerconfigjson
